### ISSUE TITLE
Problem testing locally

### ISSUE THREAD

**Issue by nlmenghini** [breadweb/extralife-helper#10]
Hello,

I wasn't sure how to get in touch with you and the the Helper forum is down so I though I might try this. I know it's not the proper use of this feature.

I'm having trouble testing locally and using the debugging tool locally. I thought I might just need to change the path for the various txt files to local documents but that doesn't seem to do anything. 

I have used used the testDonation function in the html file by changing the seconds from 0. While that does show a message it doesn't play the sound and it doesn't go away so it's not the most helpful.

Any guidance in how to properly test locally would be great thanks.

Best,
Nick

**Comment by breadweb** [comment]
Hey Nick!  Sorry for the late reply. The testing files that are there are probably pretty old and the contents may not accurately reflect the reponses from the most recent Extra Life API. With that said, the way to use them is to run a local web server on your machine and host those files and then change the Extra Life API URL to the URL of your local webserver. Hope that helps, and good luck!

**Comment by nlmenghini** [comment]
Hey,

Now worries, thanks for the information. I'll give that a try. Also thanks for making such an awesome tool for the community to use!

Nick

—

*[Nicholas Menghini]*

Product & Graphic Designer

e: [ nick.menghini@gmail.com]

w: [nicholasmenghini.com]
