### ISSUE TITLE
Multiple custom sounds plays all at once

### ISSUE THREAD

**Issue by EpicFail113** [breadweb/extralife-helper#13]
I am not sure if it was by design but putting in multiple custom sounds in the ExtraLifeHelper.html file causes all sounds listed to play at the same time on donation.

**Comment by breadweb** [comment]
Hey there! Sorry for the ridiculously late reply. 

Yes, this is by design. If you'd like to have multiple sounds play in a certain sequence, I'd suggest combining them with an audio editor.

**Comment by EpicFail113** [comment]
Thanks for the reply nonetheless, I was hoping that it would play a sound randomly versus all at once. Thanks for the clarification.
