### ISSUE TITLE
License Request

### ISSUE THREAD

**Issue by kimimaru4000** [breadweb/extralife-helper#14]
Hi, thanks for making this awesome tool! I would like to request you add a proper FLOSS license so that we're legally allowed to use this software. No license implies that standard copyright law applies and all rights are reserved; this is mentioned in the readme, though it's unclear if it's for the tool or the website.

Please see [this link](https://choosealicense.com/no-permission/) for more details. Thank you very much!

**Comment by breadweb** [comment]
Yep, that's a great request and I will find the proper licenses that applies. For now, please know that you can use the Helper freely as is and you may also download and modify the source for your own personal use. To avoid confusion with the greater Extra Life community and the existing users of Helper, I just ask that you please do not distribute modified versions.

**Comment by breadweb** [comment]
A LICENSE file has been added. Thanks again for the request.
