### ISSUE TITLE
Show total donations as progress bar

### ISSUE THREAD

**Issue by ryandesign** [breadweb/extralife-helper#15]
It might be nice if, instead of just showing the amount donated and the optional goal amount as text, it could display a progress bar like the one you see on the extra life pages e.g. at https://bit.ly/bread4kids

![progress-bar](https://user-images.githubusercontent.com/429209/195736466-9f4cc720-77fa-4a84-a7cf-c87b7ad204de.png)

**Comment by breadweb** [comment]
Thanks for the suggestion @ryandesign! I haven't updated the helper in a while so maybe I can sneak this in before game day.

**Comment by breadweb** [comment]
Wasn't able to do this before Extra Life 2023, but I am rewriting the Helper from scratch now and I will add the option to show a progress bar!
