### ISSUE TITLE
Show next donation milestone

### ISSUE THREAD

**Issue by ChaoticTeal** [breadweb/extralife-helper#18]
First off, I've been using the helper for my events for five or six years—thank you for making such a helpful, customizable tool!

With milestones being integrated into donation pages for the last couple of years, it would be really nice to include the next milestone in the rotation of things which can show up on the tracker, similar to the Extra Life and CMNH logos displaying every so often. I attempted to implement it myself last year, but I ran into some hurdles and didn't figure it out. A notification when the milestone is reached would be an added bonus!

**Comment by breadweb** [comment]
Hey! I am currently rewriting the Helper and I will definitely add the option to show your next milestone. Thanks for the suggestion. I should have added that a long time ago. :)
