### ISSUE TITLE
Light Bridge hook?

### ISSUE THREAD

**Issue by SturmB** [breadweb/extralife-helper#2]
Hey, is there any chance you could share a brief set of instructions on how to set up Philips Hue lights to flash (or change to a random color, or whatever) when you receive a donation? I cannot seem to find a way to do so via IFTTT.

**Comment by breadweb** [comment]
Hey @SturmB. I have my Hue lights flash by making a direct request to my light bridge. Assuming you are running the Helper on a computer that is connected to the same network as your light bridge, it is really easy if you use the Helper's `onNewDonation` function in `ExtraLifeHelper.html`. Here's what mine looks like:

        // If you would like additional things to happen when a new donation is 
        // received, put them in this function.
        function onNewDonation(donorName, donationAmount, message, avatarImageURL, createdOn)
        {
			$.ajax({
				url: 'http://IP-ADDRESS/api/USERNAME/groups/1/action',
				type: 'PUT',
				data: '{ "alert": "lselect" }',
				dataType: 'json',
				cache: false
			});
        }


IP-ADDRESS = The IP address of your light bridge
USERNAME = The username you created when connecting to your light bridge as explained here: https://www.developers.meethue.com/documentation/getting-started

**Comment by SturmB** [comment]
This is pretty awesome. I'll have to explore the API and maybe customize the alert to do something different, like a quick color cycle, ending on a random color or something. Thanks!
