### ISSUE TITLE
Helper not displaying properly.

### ISSUE THREAD

**Issue by jray394** [breadweb/extralife-helper#23]
Adam - Been using your EL Helper for the past 6 years or so, and I love it!

I just fired it up to test it's readiness for my personal and team goals for this year's campaign. Noticed that it doesn't appear to populate correctly after I enter my API info. 

![EL helper broken](https://github.com/user-attachments/assets/f3c26e48-4967-40e5-abfa-196412ba3b67)

Hopefully it's just a user error on my part? 

Thanks!

**Comment by breadweb** [comment]
Hey there. Can you please share a screenshot of the settings you're using and your Helper link?

**Comment by jray394** [comment]
OK. Logged back into it to get your screen caps for you and it seems to be working just fine now. Hmm.

**Comment by breadweb** [comment]
It was a temporary network issue or your IP address may have been rate limited by the Extra Life API. Is it possible you entered an incorrect participant or team ID at first?

Closing for now since you're back in business!
