### ISSUE TITLE
Live version does not match the last version of Git.

### ISSUE THREAD

**Issue by jeepee12** [breadweb/extralife-helper#8]
5 Days ago a typo in the french version was corrected, but the live version of the countdown still has the typo. Can you please update the live version? (The download link on the readme is also not up to date.)
Thank you so much for this amazing tool!! I love it!

**Comment by breadweb** [comment]
Hey @jeepee12. I have deployed the latest version of the remote Helper. Sorry for the delay and thanks for the nudge! :D  I will try to get the download version updated as well and will fix the link at the same time.

**Comment by jeepee12** [comment]
Thank you so much!!
